import { Courses } from "./course.js";
import { Department } from "./department.js";
import { Instructor } from "./instructor.js";
import { Student } from "./student.js";
import { University } from "./University.js";

let student1 = new Student("Bareera Tufail", 6, "PIAIC198253");
let student2 = new Student("Anabiya Tufail", 4, "PIAIC198253");
let student3 = new Student("Muhammad Usman", 0.3, "PIAIC198253");
let instructor1 = new Instructor("Muhammad Tufail", 34, 100_000);
let instructor2 = new Instructor("Muhammad Uzair", 32, 100_000);
let instructor3 = new Instructor("Muhammad Khubaib", 30, 100_000);
let course1 = new Courses(1, "Web 3.0 & Metaverse");
let course2 = new Courses(2, "BCC");
let course3 = new Courses(3, "AI");
let course4 = new Courses(4, "Engineering");
let piaic = new Department("PIAIC");
let aiUni = new University("AI University");
course1.addstudent(student1, student2, student3);
course2.addstudent(student1, student3, student2);
course3.addstudent(student3, student1, student2);
course4.addstudent(student2, student3, student1);
course1.addinstructor(instructor1);
course2.addinstructor(instructor1);
course3.addinstructor(instructor2);
course4.addinstructor(instructor3);
piaic.addCourse(course1, course2, course3, course4);
piaic.addfaculty(instructor1, instructor2, instructor3);
piaic.addStudent(student1, student2, student3);
aiUni.addDepartment(piaic);
console.log(aiUni.department);
